{% set name = "checklist" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 427cf87dbf47ce9f9ab059a9bbf393d9ebf967e266f8fca377420bd6995a95ac
  patches:
    - jupyter_import.patch

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - notebook
  run:
    - dill >=0.3.1
    - ipywidgets >=7.5
    - iso-639
    - munch >=2.5
    - numpy >=1.18
    - pattern
    - python >={{ python_min }}
    - spacy >=2.2
    - transformers >=2.8
    - notebook

test:
  requires:
    - python {{ python_min }}
  imports:
    - checklist
    - checklist.viewer
    - checklist.viewer.static

about:
  home: http://github.com/marcotcr/checklist
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Beyond Accuracy: Behavioral Testing of NLP Models with CheckList'
  dev_url: http://github.com/marcotcr/checklist

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
